###############

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MIRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 200
  LR_INITIAL: 2e-4
  WARMUP: 1
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 128
  RESUME: False
  TRAIN_DIR: './data/train' # path to training data
  VAL_DIR: './data/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: 1
  #VAL_AFTER_EVERY: 1
